# https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "thomas-illiet"
    labels:
      - "nuget dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "thomas-illiet"
    labels:
      - "github dependencies"
  - package-ecosystem: "docker"
    directory: "/docker/db"
    schedule:
      interval: "daily"
    reviewers:
      - "thomas-illiet"
    labels:
      - "docker dependencies"
  - package-ecosystem: "docker"
    directory: "/docker/service"
    schedule:
      interval: "daily"
    reviewers:
      - "thomas-illiet"
    labels:
      - "docker dependencies"
