version: '3.7'

services:

  netboot_service:
    build: docker/service
    volumes:
      - /docker/data/netboot/vault/data:/data
    networks:
      webgateway: {}
      default: {}
    environment:
      - DOMAIN=https://vault.netboot.fr
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - WEBSOCKET_ENABLED=true
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@netboot_db:5432/vault
      - SIGNUPS_ALLOWED=false
      - INVITATIONS_ALLOWED=true
      - EMERGENCY_ACCESS_ALLOWED=true
      - TZ=Europe/Paris
    depends_on:
      netboot_db:
        condition: service_healthy
    labels:
      # TRAEFIK CONFIG
      - "traefik.enable=true"
      - "traefik.docker.network=webgateway"
      # ROUTER AND SERVICE DEFINITION
      - "traefik.http.routers.vault.entryPoints=websecure"
      - "traefik.http.routers.vault.tls=true"
      - "traefik.http.routers.vault.service=vault"
      - "traefik.http.routers.vault.rule=Host(`vault.netboot.fr`)"
      - "traefik.http.routers.vault.tls.certresolver=letsencrypt"
      - "traefik.http.services.vault.loadbalancer.server.port=80"
      - "traefik.http.services.vault.loadbalancer.server.scheme=http"
      # WEBSOCKET ROUTER AND SERVICE DEFINITION
      - "traefik.http.routers.vault-websocket.entrypoints=websecure"
      - "traefik.http.routers.vault-websocket.rule=Host(`vault.netboot.fr`) && Path(`/notifications/hub`)"
      - "traefik.http.routers.vault-websocket.service=vault-websocket"
      - "traefik.http.services.vault-websocket.loadbalancer.server.port=3012"
      - "traefik.http.routers.vault-websocket.tls=true"
      - "traefik.http.routers.vault-websocket.tls.certresolver=letsencrypt"
      # HTTPS HEADERS
      - "traefik.http.middlewares.vault.headers.SSLRedirect=true"
      - "traefik.http.middlewares.vault.headers.STSSeconds=315360000"
      - "traefik.http.middlewares.vault.headers.browserXSSFilter=true"
      - "traefik.http.middlewares.vault.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.vault.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.vault.headers.STSIncludeSubdomains=true"
      - "traefik.http.middlewares.vault.headers.STSPreload=true"
      - "traefik.http.middlewares.vault.headers.frameDeny=true"
    healthcheck:
      test: ["CMD", "curl", "-kILs", "--fail", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  netboot_db:
    build: docker/db
    networks:
      default: {}
    environment:
      POSTGRES_DB: vault
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /docker/data/netboot/vault/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

networks:
  webgateway:
    external: true
