name: Build
on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  schedule:
    - cron: '0 5 * * *'
jobs:
  build:
    runs-on: [azure]
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v4
      - name: Setup environment variables
        env:
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          ADMIN_TOKEN: ${{secrets.ADMIN_TOKEN}}
        run: |
          touch .env
          echo DB_USERNAME='${{ secrets.DB_USERNAME }}' >> .env
          echo DB_PASSWORD='${{ secrets.DB_PASSWORD }}' >> .env
          echo ADMIN_TOKEN='${{ secrets.ADMIN_TOKEN }}' >> .env
      - name: Stop Containers
        run: "sudo /usr/local/bin/docker-compose -p vault stop"
      - name: Start Containers
        run: "sudo /usr/local/bin/docker-compose -p vault up -d --build"
